services:
  - type: web
    name: massage-salon-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: 20
